apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
  name: httpd-example
  namespace: "{{ .Values.environmentName }}-dev"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: httpd-example:latest
  source:
    git:
      uri: https://github.com/sclorg/httpd-ex.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: httpd:2.4-el8
        namespace: openshift
    type: Source
  triggers:
  - type: ImageChange
  - type: ConfigChange

