apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: httpd-example-route
  namespace: "{{ .Values.environmentName }}-dev"
spec:
  host: "iwork.apps.ocp5.bofh.ninja"
  to:
    kind: Service
    name: httpd-example

