apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: httpd-example-route
  namespace: "testapp123-dev"
spec:
  host: "iwork.apps.cluster-kpmc8.kpmc8.sandbox944.opentlc.com"
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: httpd-example
