apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: httpd-example-route
  namespace: "rti"
spec:
  host: "iwork.apps.ocp5.bofh.ninja"
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: httpd-example
