apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
  name: httpd-example
  namespace: "{{ .Values.environmentName }}-dev"
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    name: httpd-example

